In [40]:
from urllib.request import urlopen
import json
import pandas as pd
import plotly.express as px

In [41]:
url="https://api.openf1.org/v1"
table="meetings"

In [42]:
monza23 = json.loads(urlopen(url+"/"+table+"?year=2023&location=Monza").read().decode('utf-8'))
monza23

[{'meeting_name': 'Italian Grand Prix',
  'meeting_official_name': 'FORMULA 1 PIRELLI GRAN PREMIO Dâ€™ITALIA 2023',
  'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'date_start': '2023-09-01T11:30:00+00:00',
  'gmt_offset': '02:00:00',
  'meeting_key': 1218,
  'year': 2023}]

In [43]:
max23_laps=json.loads(urlopen(url+"/"+"laps?meeting_key=1218&driver_number=1&session_key=9157").read().decode('utf-8'))
max23_laps=pd.DataFrame(max23_laps)
max23_laps.head()

,meeting_key,session_key,driver_number,i1_speed,i2_speed,st_speed,date_start,lap_duration,is_pit_out_lap,duration_sector_1,duration_sector_2,duration_sector_3,segments_sector_1,segments_sector_2,segments_sector_3,lap_number
0,1218,9157,1,320.0,307.0,285.0,None,NaN,False,NaN,29.666,28.473,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 2049]","[2049, 2049, 2049, 2049, 2049, 2049, 2049]","[2049, 2051, 2049, 2049, 2048, 2049, 2048, 204...",1
1,1218,9157,1,309.0,309.0,305.0,2023-09-03T13:24:50.909000+00:00,86.163,False,28.274,29.543,28.346,"[2049, 2049, 2048, 2049, 2048, 2048, 2049, 2048]","[2049, 2049, 2048, 2048, 2049, 2049, 2049]","[2049, 2048, 2051, 2049, 2048, 2049, 2049, 204...",2
2,1218,9157,1,310.0,320.0,309.0,2023-09-03T13:26:17.158000+00:00,85.702,False,28.097,29.320,28.285,"[None, 2048, 2049, 2049, 2048, 2049, 2049, 2048]","[2049, 2049, 2048, 2048, 2048, 2051, 2049]","[2049, 2048, 2048, 2049, 2048, 2048, 2048, 204...",3
3,1218,9157,1,311.0,320.0,318.0,2023-09-03T13:27:42.736000+00:00,86.050,False,28.145,29.474,28.431,"[None, 2049, 2048, 2048, 2048, 2048, 2049, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2049, 2049, 2049, 2049, 2048, 204...",4
4,1218,9157,1,NaN,321.0,317.0,2023-09-03T13:29:08.907000+00:00,86.176,False,28.155,29.514,28.507,"[None, 2049, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2049, 2048, 2048, 2048, 2049]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",5

In [44]:
max24_laps=json.loads(urlopen(url+"/"+"laps?meeting_key=1244&driver_number=1&session_key=9590").read().decode('utf-8'))
max24_laps=pd.DataFrame(max24_laps)
max24_laps.head()

,meeting_key,session_key,driver_number,i1_speed,i2_speed,st_speed,date_start,lap_duration,is_pit_out_lap,duration_sector_1,duration_sector_2,duration_sector_3,segments_sector_1,segments_sector_2,segments_sector_3,lap_number
0,1244,9590,1,327.0,316,298.0,None,NaN,False,NaN,31.144,28.856,"[2048, 2049, 2049, 2049, 2049, 2049]","[2049, 2049, 2049, 2049, 2049, 2049, 2049]","[2049, 2049, 2048, 2048, 2049, 2049, 2048, 2048]",1
1,1244,9590,1,315.0,334,316.0,2024-09-01T13:05:05.139000+00:00,86.170,False,28.048,29.474,28.648,"[2049, 2049, 2049, 2049, 2048, 2048]","[2049, 2049, 2049, 2049, 2049, 2049, 2049]","[2049, 2048, 2048, 2048, 2049, 2049, 2049, 2048]",2
2,1244,9590,1,314.0,332,321.0,2024-09-01T13:06:31.369000+00:00,85.855,False,27.731,29.496,28.628,"[None, 2049, 2049, 2049, 2048, 2048]","[2049, 2048, 2048, 2048, 2049, 2048, 2048]","[2048, 2049, 2048, 2048, 2049, 2049, 2048, 2048]",3
3,1244,9590,1,313.0,318,317.0,2024-09-01T13:07:57.173000+00:00,85.633,False,27.884,29.335,28.414,"[2048, 2048, 2049, 2048, 2048, 2048]","[2049, 2049, 2048, 2049, 2049, 2048, 2048]","[2048, 2049, 2048, 2048, 2049, 2049, 2049, 2048]",4
4,1244,9590,1,NaN,318,NaN,2024-09-01T13:09:22.864000+00:00,85.218,False,27.721,29.220,28.277,"[None, 2048, 2048, 2049, 2048, 2048]","[2049, 2048, 2048, 2049, 2049, 2048, 2048]","[2048, 2049, 2049, 2048, 2048, 2049, 2049, 2048]",5

In [45]:
max_monza_laps=max23_laps[["lap_duration","lap_number"]].merge(max24_laps[["lap_duration","lap_number"]], on="lap_number", suffixes=('_23', '_24'))
max_monza_laps.head()

   lap_duration_23  lap_number  lap_duration_24
0              NaN           1              NaN
1           86.163           2           86.170
2           85.702           3           85.855
3           86.050           4           85.633
4           86.176           5           85.218

In [46]:
max23_stints=json.loads(urlopen(url+"/"+"stints?meeting_key=1218&driver_number=1&session_key=9157").read().decode('utf-8'))
max23_stints=pd.DataFrame(max23_stints)
max23_stints.head()

,meeting_key,session_key,stint_number,driver_number,lap_start,lap_end,compound,tyre_age_at_start
0,1218,9157,1,1,1,20,MEDIUM,0
1,1218,9157,2,1,21,52,HARD,0

In [47]:
max24_stints=json.loads(urlopen(url+"/"+"stints?meeting_key=1244&driver_number=1&session_key=9590").read().decode('utf-8'))
max24_stints=pd.DataFrame(max24_stints)
max24_stints.head()

,meeting_key,session_key,stint_number,driver_number,lap_start,lap_end,compound,tyre_age_at_start
0,1244,9590,1,1,1,22,HARD,0
1,1244,9590,2,1,23,41,HARD,0
2,1244,9590,3,1,42,54,MEDIUM,0

In [48]:
max23_stints["lap_number"]=max23_stints.apply(lambda x: list(range(x["lap_start"],x["lap_end"]+1)), axis=1)
max23_stints=max23_stints.explode("lap_number")
max23_stints

,meeting_key,session_key,stint_number,driver_number,lap_start,lap_end,compound,tyre_age_at_start,lap_number
0,1218,9157,1,1,1,20,MEDIUM,0,1
0,1218,9157,1,1,1,20,MEDIUM,0,2
0,1218,9157,1,1,1,20,MEDIUM,0,3
0,1218,9157,1,1,1,20,MEDIUM,0,4
0,1218,9157,1,1,1,20,MEDIUM,0,5
0,1218,9157,1,1,1,20,MEDIUM,0,6
0,1218,9157,1,1,1,20,MEDIUM,0,7
0,1218,9157,1,1,1,20,MEDIUM,0,8
0,1218,9157,1,1,1,20,MEDIUM,0,9
0,1218,9157,1,1,1,20,MEDIUM,0,10
0,1218,9157,1,1,1,20,MEDIUM,0,11
0,1218,9157,1,1,1,20,MEDIUM,0,12
0,1218,9157,1,1,1,20,MEDIUM,0,13
0,1218,9157,1,1,1,20,MEDIUM,0,14
0,1218,9157,1,1,1,20,MEDIUM,0,15
0,1218,9157,1,1,1,20,MEDIUM,0,16
0,1218,9157,1,1,1,20,MEDIUM,0,17
0,1218,9157,1,1,1,20,MEDIUM,0,18
0,1218,9157,1,1,1,20,MEDIUM,0,19
0,1218,9157,1,1,1,20,MEDIUM,0,20
1,1218,9157,2,1,21,52,HARD,0,21
1,1218,9157,2,1,21,52,HARD,0,22
1,1218,9157,2,1,21,52,HARD,0,23
1,1218,9157,2,1,21,52,HARD,0,24
1,1218,9157,2,1,21,52,HARD,0,25
1,1218,9157,2,1,21,52,HARD,0,26
1,1218,9157,2,1,21,52,HARD,0,27
1,1218,9157,2,1,21,52,HARD,0,28
1,1218,9157,2,1,21,52,HARD,0,29
1,1218,9157,2,1,21,52,HARD,0,30
1,1218,9157,2,1,21,52,HARD,0,31
1,1218,9157,2,1,21,52,HARD,0,32
1,1218,9157,2,1,21,52,HARD,0,33
1,1218,9157,2,1,21,52,HARD,0,34
1,1218,9157,2,1,21,52,HARD,0,35
1,1218,9157,2,1,21,52,HARD,0,36
1,1218,9157,2,1,21,52,HARD,0,37
1,1218,9157,2,1,21,52,HARD,0,38
1,1218,9157,2,1,21,52,HARD,0,39
1,1218,9157,2,1,21,52,HARD,0,40
1,1218,9157,2,1,21,52,HARD,0,41
1,1218,9157,2,1,21,52,HARD,0,42
1,1218,9157,2,1,21,52,HARD,0,43
1,1218,9157,2,1,21,52,HARD,0,44
1,1218,9157,2,1,21,52,HARD,0,45
1,1218,9157,2,1,21,52,HARD,0,46
1,1218,9157,2,1,21,52,HARD,0,47
1,1218,9157,2,1,21,52,HARD,0,48
1,1218,9157,2,1,21,52,HARD,0,49
1,1218,9157,2,1,21,52,HARD,0,50
1,1218,9157,2,1,21,52,HARD,0,51
1,1218,9157,2,1,21,52,HARD,0,52

In [49]:
# make the max24_stints table with lap number from 1 to 54 from lap_start to lap_end and have the corresponding compound
max24_stints["lap_number"]=max24_stints.apply(lambda x: list(range(x["lap_start"],x["lap_end"]+1)), axis=1)
max24_stints=max24_stints.explode("lap_number")
max24_stints

,meeting_key,session_key,stint_number,driver_number,lap_start,lap_end,compound,tyre_age_at_start,lap_number
0,1244,9590,1,1,1,22,HARD,0,1
0,1244,9590,1,1,1,22,HARD,0,2
0,1244,9590,1,1,1,22,HARD,0,3
0,1244,9590,1,1,1,22,HARD,0,4
0,1244,9590,1,1,1,22,HARD,0,5
0,1244,9590,1,1,1,22,HARD,0,6
0,1244,9590,1,1,1,22,HARD,0,7
0,1244,9590,1,1,1,22,HARD,0,8
0,1244,9590,1,1,1,22,HARD,0,9
0,1244,9590,1,1,1,22,HARD,0,10
0,1244,9590,1,1,1,22,HARD,0,11
0,1244,9590,1,1,1,22,HARD,0,12
0,1244,9590,1,1,1,22,HARD,0,13
0,1244,9590,1,1,1,22,HARD,0,14
0,1244,9590,1,1,1,22,HARD,0,15
0,1244,9590,1,1,1,22,HARD,0,16
0,1244,9590,1,1,1,22,HARD,0,17
0,1244,9590,1,1,1,22,HARD,0,18
0,1244,9590,1,1,1,22,HARD,0,19
0,1244,9590,1,1,1,22,HARD,0,20
0,1244,9590,1,1,1,22,HARD,0,21
0,1244,9590,1,1,1,22,HARD,0,22
1,1244,9590,2,1,23,41,HARD,0,23
1,1244,9590,2,1,23,41,HARD,0,24
1,1244,9590,2,1,23,41,HARD,0,25
1,1244,9590,2,1,23,41,HARD,0,26
1,1244,9590,2,1,23,41,HARD,0,27
1,1244,9590,2,1,23,41,HARD,0,28
1,1244,9590,2,1,23,41,HARD,0,29
1,1244,9590,2,1,23,41,HARD,0,30
1,1244,9590,2,1,23,41,HARD,0,31
1,1244,9590,2,1,23,41,HARD,0,32
1,1244,9590,2,1,23,41,HARD,0,33
1,1244,9590,2,1,23,41,HARD,0,34
1,1244,9590,2,1,23,41,HARD,0,35
1,1244,9590,2,1,23,41,HARD,0,36
1,1244,9590,2,1,23,41,HARD,0,37
1,1244,9590,2,1,23,41,HARD,0,38
1,1244,9590,2,1,23,41,HARD,0,39
1,1244,9590,2,1,23,41,HARD,0,40
1,1244,9590,2,1,23,41,HARD,0,41
2,1244,9590,3,1,42,54,MEDIUM,0,42
2,1244,9590,3,1,42,54,MEDIUM,0,43
2,1244,9590,3,1,42,54,MEDIUM,0,44
2,1244,9590,3,1,42,54,MEDIUM,0,45
2,1244,9590,3,1,42,54,MEDIUM,0,46
2,1244,9590,3,1,42,54,MEDIUM,0,47
2,1244,9590,3,1,42,54,MEDIUM,0,48
2,1244,9590,3,1,42,54,MEDIUM,0,49
2,1244,9590,3,1,42,54,MEDIUM,0,50
2,1244,9590,3,1,42,54,MEDIUM,0,51
2,1244,9590,3,1,42,54,MEDIUM,0,52
2,1244,9590,3,1,42,54,MEDIUM,0,53
2,1244,9590,3,1,42,54,MEDIUM,0,54

In [57]:
max_stints=max23_stints[["lap_number","compound"]].merge(max24_stints[["lap_number","compound"]], on="lap_number", suffixes=('_23', '_24'),how="outer")
max_stints.head()

C:\Users\kjmak\AppData\Local\Temp\ipykernel_24328\2561108852.py:1: FutureWarning:

In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)

  lap_number compound_23 compound_24
0        1.0      MEDIUM        HARD
1        2.0      MEDIUM        HARD
2        3.0      MEDIUM        HARD
3        4.0      MEDIUM        HARD
4        5.0      MEDIUM        HARD

In [58]:
max_monza_laps=max_monza_laps.merge(max_stints, on="lap_number")

In [59]:
max_monza_laps.head()

   lap_duration_23 lap_number  lap_duration_24 compound_23 compound_24
0              NaN          1              NaN      MEDIUM        HARD
1           86.163          2           86.170      MEDIUM        HARD
2           85.702          3           85.855      MEDIUM        HARD
3           86.050          4           85.633      MEDIUM        HARD
4           86.176          5           85.218      MEDIUM        HARD

In [70]:
#update the plot to have a black background and have a different color line for tyre compounds, White for HARD and yellow for MEDIUM
fig=px.line(max_monza_laps, x="lap_number", y=["lap_duration_23", "lap_duration_24"], title="Max Verstappen Monza 2023 vs 2024", template="plotly_dark", color="compound_23")
# fig=px.line(max_monza_laps, x="lap_number", y=["lap_duration_23", "lap_duration_24"], title="Max Verstappen Monza 2023 vs 2024")
#the lines should be of different hues for different years but stints should be of the same color
fig=px.line(max_monza_laps, x="lap_number", y=["lap_duration_23", "lap_duration_24"], title="Max Verstappen Monza 2023 vs 2024", color="compound_23")
#colors are not white and yellow
fig=px.line(max_monza_laps, x="lap_number", y=["lap_duration_23", "lap_duration_24"], title="Max Verstappen Monza 2023 vs 2024", template="plotly_dark", color_discrete_map={"HARD":"white","MEDIUM":"yellow"})
fig.update_coloraxes(colorbar_title="Tyre compound")
fig.update_traces(mode="markers+lines")
fig.update_yaxes(title_text="Lap duration (s)")
fig.update_xaxes(title_text="Lap number")
fig.show()

In [54]:
monza23_sessions=json.loads(urlopen(url+"/"+"sessions?meeting_key=1218").read().decode('utf-8'))
monza23_sessions

[{'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'session_type': 'Practice',
  'session_name': 'Practice 1',
  'date_start': '2023-09-01T11:30:00+00:00',
  'date_end': '2023-09-01T12:30:00+00:00',
  'gmt_offset': '02:00:00',
  'session_key': 9150,
  'meeting_key': 1218,
  'year': 2023},
 {'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'session_type': 'Practice',
  'session_name': 'Practice 2',
  'date_start': '2023-09-01T15:00:00+00:00',
  'date_end': '2023-09-01T16:00:00+00:00',
  'gmt_offset': '02:00:00',
  'session_key': 9151,
  'meeting_key': 1218,
  'year': 2023},
 {'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'session_type': 'Practice',
  'session_name': 'Practice 3',
  'date_start': '2023-09-02T10:30:00+00:00',
  'date_end': '2023-09-02T11:30:00+00:00',
  'gmt_offset': '02:00:00',
  'session_key': 9152,
  'meeting_key': 1218,
  'year': 2023},
 {'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'session_type': 'Qualifying',
  'session_name': 'Qualifying',
  'date_start': '2023-09-02T14:00:00+00:00',
  'date_end': '2023-09-02T15:00:00+00:00',
  'gmt_offset': '02:00:00',
  'session_key': 9153,
  'meeting_key': 1218,
  'year': 2023},
 {'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'session_type': 'Race',
  'session_name': 'Race',
  'date_start': '2023-09-03T13:00:00+00:00',
  'date_end': '2023-09-03T15:00:00+00:00',
  'gmt_offset': '02:00:00',
  'session_key': 9157,
  'meeting_key': 1218,
  'year': 2023}]

In [55]:
monza24_sessions=json.loads(urlopen(url+"/"+"sessions?meeting_key=1244").read().decode('utf-8'))
monza24_sessions

[{'session_key': 9583,
  'session_name': 'Practice 1',
  'date_start': '2024-08-30T11:30:00+00:00',
  'date_end': '2024-08-30T12:30:00+00:00',
  'gmt_offset': '02:00:00',
  'session_type': 'Practice',
  'meeting_key': 1244,
  'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'year': 2024},
 {'session_key': 9584,
  'session_name': 'Practice 2',
  'date_start': '2024-08-30T15:00:00+00:00',
  'date_end': '2024-08-30T16:00:00+00:00',
  'gmt_offset': '02:00:00',
  'session_type': 'Practice',
  'meeting_key': 1244,
  'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'year': 2024},
 {'session_key': 9585,
  'session_name': 'Practice 3',
  'date_start': '2024-08-31T10:30:00+00:00',
  'date_end': '2024-08-31T11:30:00+00:00',
  'gmt_offset': '02:00:00',
  'session_type': 'Practice',
  'meeting_key': 1244,
  'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'year': 2024},
 {'session_key': 9586,
  'session_name': 'Qualifying',
  'date_start': '2024-08-31T14:00:00+00:00',
  'date_end': '2024-08-31T15:00:00+00:00',
  'gmt_offset': '02:00:00',
  'session_type': 'Qualifying',
  'meeting_key': 1244,
  'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'year': 2024},
 {'session_key': 9590,
  'session_name': 'Race',
  'date_start': '2024-09-01T13:00:00+00:00',
  'date_end': '2024-09-01T15:00:00+00:00',
  'gmt_offset': '02:00:00',
  'session_type': 'Race',
  'meeting_key': 1244,
  'location': 'Monza',
  'country_key': 13,
  'country_code': 'ITA',
  'country_name': 'Italy',
  'circuit_key': 39,
  'circuit_short_name': 'Monza',
  'year': 2024}]

In [56]:
pd.DataFrame(data)

,meeting_name,meeting_official_name,location,country_key,country_code,country_name,circuit_key,circuit_short_name,date_start,gmt_offset,meeting_key,year
0,Italian Grand Prix,FORMULA 1 PIRELLI GRAN PREMIO Dâ€™ITALIA 2023,Monza,13,ITA,Italy,39,Monza,2023-09-01T11:30:00+00:00,02:00:00,1218,2023